version: "3"
services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "/etc/redis/redis.conf"]
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data
      - ./redis.conf:/etc/redis/redis.conf

  api:
    depends_on:
      - redis
    image: developomp/exyleio-api:latest
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./api_log:/log

  web:
    depends_on:
      - api
    restart: unless-stopped
    ports:
      - 5173:5173
    build: .
    volumes:
      - .:/app
