name: Deploy to Firebase Hosting on PR
on:
  pull_request:
    paths-ignore:
      - "README.md"
jobs:
  build:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build
  deploy:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: build
      - name: Set target
        uses: w9jds/firebase-action@master
        with:
          args: use exyleio
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EXYLEIO }}
      - name: Apply target
        uses: w9jds/firebase-action@master
        with:
          args: target:apply hosting exyleio-web exyleio-web
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EXYLEIO }}
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EXYLEIO }}
